service: starkoverflow-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  cronHandler:
    handler: index.run
    events:
      # Invoke Lambda function every 10 minutes minute from Mon-Sun
      #  - schedule: cron(0/10 * ? * SUN-SAT *)
      - schedule: cron(0/10 * ? * * *)
